######### Cadastro tópico

POST http://127.0.0.1:3333/universo HTTP/1.1
Content-Type: application/json
Authorization: Bearer Mg.9xAnO_6CY0l7xnUlSD3bwcgk4wmrURQWVHoEp7op6AMnSuMpE08Mo8f3GMwS

{
    "name": "Universo I ",
    "apelido": "Estrela",
    "planeta": "Terra "
}

######### Listar todos os tópicos
GET http://127.0.0.1:3333/universo HTTP/1.1
Content-Type: application/json
Authorization: Bearer Mg.9xAnO_6CY0l7xnUlSD3bwcgk4wmrURQWVHoEp7op6AMnSuMpE08Mo8f3GMwS

######### Listar Tópico específico
GET http://127.0.0.1:3333/universo/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer Mg.9xAnO_6CY0l7xnUlSD3bwcgk4wmrURQWVHoEp7op6AMnSuMpE08Mo8f3GMwS

######### Alterar Tópico
PUT http://127.0.0.1:3333/universo/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer Mg.9xAnO_6CY0l7xnUlSD3bwcgk4wmrURQWVHoEp7op6AMnSuMpE08Mo8f3GMwS

{
    "name": "UNiverso II",
    "apelido": "Estrela",
    "planeta": "Terra "
}

######### Apagar Tópicos
DELETE http://127.0.0.1:3333/universo/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer Mg.9xAnO_6CY0l7xnUlSD3bwcgk4wmrURQWVHoEp7op6AMnSuMpE08Mo8f3GMwS